apiVersion: 1

datasources:
  - name: InfluxDB_v2_Flux
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    user: $INFLUXDB_USERNAME
    secureJsonData:
      token: $INFLUXDB_ACCESS_TOKEN
    jsonData:
      version: Flux
      organization: home
      defaultBucket: sensor-data
      tlsSkipVerify: true
